FROM node:20-alpine AS base
RUN apk add -U build-base python3 py3-setuptools make g++ git
WORKDIR /usr/src/app
RUN npm install -g pnpm@9.4.0
COPY package.json pnpm-lock.yaml ./

FROM base AS prod-deps
RUN pnpm install --prod --frozen-lockfile --ignore-scripts
COPY . .
RUN cd node_modules/node-pty && npm run install && cd ../..
RUN cd node_modules/.pnpm/gc-stats@1.4.1/node_modules/gc-stats && npm run install

FROM base AS build
RUN pnpm install --frozen-lockfile
COPY . .
RUN pnpm run build

FROM node:20-alpine
LABEL maintainer="butlerx@notthe.cloud"
RUN apk add -U coreutils openssh-client sshpass && addgroup -S app && adduser -S app -G app
WORKDIR /usr/src/app
ENV NODE_ENV=production
ENV PORT=3000
COPY --from=prod-deps /usr/src/app/node_modules ./node_modules
COPY --from=build /usr/src/app/build ./build
COPY package.json ./
RUN mkdir -p /home/app/.ssh && chown -R app:app /home/app /usr/src/app
USER app
EXPOSE 3000
CMD ["node", "."]
