apiVersion: v1
kind: Config
clusters:
- cluster:
    server: https://my-aks-cluster.hcp.eastus.azmk8s.io
  name: my-aks-cluster
contexts:
- context:
    cluster: my-aks-cluster
    user: clusterUser
  name: my-aks-cluster
current-context: my-aks-cluster
users:
- name: clusterUser
